Branch v1.3 diagrams
AY2223S2-CS2103T-W14-4/tp pull request #112
Opened 2023-03-27 13:34 UTC by Merrickneo

## What
1. Edit broken links for the filepaths for activity diagrams
2. Refactor AddressBookStorage to HMHeroStorage
3. Add diagrams for the `list` and `reject` commands

Fix #109

2023-03-28 07:43 UTC, FredericChow00 requested changes
some minor changes

2023-03-28 07:43 UTC, FredericChow00 commented on docs/images/StorageClassDiagram.png
arrows are glitched out

2023-03-28 10:34 UTC, Jxleejiaxin reviewed
Just some minor reminders. Thanks for refactoring everything!

2023-03-28 10:34 UTC, Jxleejiaxin commented on docs/images/RejectApplicantActivityDiagram.png
Missing check if applicant is already `REJECTED` status.

2023-03-28 10:34 UTC, Jxleejiaxin commented on docs/diagrams/EditApplicantActivityDiagram.puml
I am assuming this is a placeholder?

2023-03-28 10:34 UTC, Jxleejiaxin commented on src/main/java/seedu/address/logic/parser/AddCommandParser.java
> +            throw new ParseException("Application Date cannot be in the future!");
Need to edit `add` activity diagram and feature implementation in DG.

2023-03-28 12:38 UTC, Merrickneo commented on src/main/java/seedu/address/logic/parser/AddCommandParser.java
> +            throw new ParseException("Application Date cannot be in the future!");
Ok done!

2023-03-28 15:43 UTC, Merrickneo commented
I have to refactor some more classes for the `Storage` component! Will update here when i'm done.

2023-03-29 02:51 UTC, FredericChow00 approved these changes
LGTM!

2023-03-29 08:35 UTC, merged