Update DG: Design, Architecture, UI, Logic
AY2223S2-CS2103T-W14-4/tp pull request #114
Opened 2023-03-28 03:36 UTC by dunliang0513

2023-03-28 07:30 UTC, FredericChow00 requested changes
left some comments!

2023-03-28 07:30 UTC, FredericChow00 commented on docs/DeveloperGuide.md
> +3. The stylesheets for these UI parts can be found in `Extensions.css` and `Mainwindow.css`, except `UserProfilePanel` and `HelpWindow` with separate CSS files in matching `.css` files in the [`src/m
add in HMHero.css too

2023-03-28 10:17 UTC, Merrickneo commented on docs/images/StorageClassDiagram.png
@dunliang0513 @FredericChow00 I've done it in my PR don't worry about the refactoring!

2023-03-28 10:35 UTC, dunliang0513 commented on docs/DeveloperGuide.md
> +3. The stylesheets for these UI parts can be found in `Extensions.css` and `Mainwindow.css`, except `UserProfilePanel` and `HelpWindow` with separate CSS files in matching `.css` files in the [`src/m
OK~

2023-03-29 02:52 UTC, FredericChow00 approved these changes
LGTM!

2023-03-29 02:53 UTC, merged