Implement NoteContainsKeywordsPredicateTest and PhoneContainsKeywordsPredicateTest
AY2223S2-CS2103T-W14-4/tp pull request #173
Opened 2023-04-06 09:27 UTC by bofeng1999

## What
Implement `NoteContainsKeywordsPredicateTest`  and `PhoneContainsKeywordsPredicateTest`

## Why
Test cases are written to ensure that NoteContainsKeywordsPredicate` and  `PhoneContainsKeywordsPredicateTest` is working according to its business logic.

2023-04-07 07:29 UTC, FredericChow00 requested changes
Left minor comments on grammar

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You run the interview command.
I think dont need this line `You run the interview command` since this is the interview command already

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You run the edit command.
I think dont need this line since this is the edit command already

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You run the remind command.
dont need this line too

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You run the summary command.
dont need this line

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You run the advance command.
dont need this line

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You run the advance command.
dont need this line

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You want to advance an applicant's status `SHORTLISTED` who exist in HMHero yet.
remove "yet"

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You want to reject an applicant's status `SHORTLISTED` who exist in HMHero yet.
remove "yet"

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You run the reject command.
dont need this line

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You want to list the interview dates of the shortlisted applicants who exist in HMHero yet.
dont need yet

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You want to create a new applicant named Adam whose information does not exist in HMHero yet.
dont need "yet"

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You run the add command with his details following the above format.
dont need this line

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You run the find command with his details following the above format.
dont need this line

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You want to search for an applicant named Adam whose information exist in HMHero yet.
dont neet yet

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You want to list all applicants who exist in HMHero yet.
dont need "yet"

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You run the list command.
dont need this line

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You want to delete an applicant who exist in HMHero yet.
dont need "yet"

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You run the delete command.
dont need this line

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You want to edit the phone number and notes of an applicant who exist in HMHero yet.
dont need "yet"

2023-04-07 07:29 UTC, FredericChow00 commented on docs/UserGuide.md
> +* You want to see all the applicants with interview within the next three days who exist in HMHero yet.
dont need "yet"

2023-04-08 04:27 UTC, bofeng1999 commented on docs/UserGuide.md
> +* You want to see all the applicants with interview within the next three days who exist in HMHero yet.
edited!

2023-04-08 04:27 UTC, bofeng1999 commented on docs/UserGuide.md
> +* You want to edit the phone number and notes of an applicant who exist in HMHero yet.
edited!

2023-04-08 04:27 UTC, bofeng1999 commented on docs/UserGuide.md
> +* You run the delete command.
edited!

2023-04-08 04:27 UTC, bofeng1999 commented on docs/UserGuide.md
> +* You want to delete an applicant who exist in HMHero yet.
edited!

2023-04-08 04:27 UTC, bofeng1999 commented on docs/UserGuide.md
> +* You run the list command.
edited!

2023-04-08 04:27 UTC, bofeng1999 commented on docs/UserGuide.md
> +* You run the advance command.
edited!

2023-04-08 04:27 UTC, bofeng1999 commented on docs/UserGuide.md
> +* You run the summary command.
edited!

2023-04-08 04:28 UTC, bofeng1999 commented on docs/UserGuide.md
> +* You run the remind command.
edited!

2023-04-08 04:28 UTC, bofeng1999 commented on docs/UserGuide.md
> +* You run the edit command.
okays, i remove all these lines

2023-04-08 04:28 UTC, bofeng1999 commented on docs/UserGuide.md
> +* You run the interview command.
edited!

2023-04-08 05:45 UTC, FredericChow00 approved these changes
LGTM!

2023-04-08 05:45 UTC, merged