Wrote ApplicationDateTime and ApplicationDateTimeTest
AY2223S2-CS2103T-W14-4/tp pull request #66
Opened 2023-03-16 14:10 UTC by FredericChow00

## What
Implemented `ApplicationDateTime` class and wrote `ApplicationDateTimeTest`

## Why
Allows HMHero to track the application date of applicants when they get added into the application.

Test cases are written to ensure that `ApplicationDateTime` is working according to its business logic.

## How
Add `ApplicationDateTime` field to `Person`. This will allow future implemented commands to track the date and time that the applicant applied to the company.

Adds full path coverage for `ApplicationDateTime`

Fix #64

2023-03-18 13:35 UTC, bofeng1999 approved these changes
LGTM!

2023-03-20 06:08 UTC, Jxleejiaxin requested changes
Need to update JsonAdaptedPerson to save ApplicationDateTime to json file

2023-03-20 16:22 UTC, Jxleejiaxin requested changes

2023-03-20 16:22 UTC, Jxleejiaxin commented on src/main/java/seedu/address/model/person/Person.java
> +        this.applicationDateTime = new ApplicationDateTime(LocalDateTime.now().truncatedTo(ChronoUnit.MINUTES));
`Person.applicantDateTime` is renewed everytime a `Person` object is created. When converting from `JsonAdaptedPerson` to `Person` object, this constructor is called again, thus effectively "refreshing" the `applicationDateTime`

What should be done is getting `LocalDateTime.now()` when `AddCommand` is used. Then, we are able to save the actual dateTime the applicant was added (applied). `Person` constructor needs to accept an additional `applicationDateTime` parameter to convert from `Person` to `JsonAdaptedPerson` and vice-versa.

2023-03-21 08:14 UTC, merged