Enhance find command
AY2223S2-CS2103T-W14-4/tp pull request #67
Opened 2023-03-17 09:48 UTC by Jxleejiaxin

## What
Add function in find command parser to allow searching for applicants based on note.
Improve code quality of find command.

## Why
Allow hiring managers to find applicants with specific skillsets that are relevant to the job.

## How
By replacing all the fields in `FindCommand` with `Predicate<Person>`, subsequent enhancements to find command only requires `FindCommandParser` to add on to the predicate using `Predicate<T>`'s `or` `and` methods, rather than adding new fields into `FindCommand`.

To Do: add more test cases for `FindCommand`

Fix #62

2023-03-18 14:02 UTC, FredericChow00 approved these changes
LGTM!

2023-03-19 12:35 UTC, Merrickneo requested changes
Gradle is complaining about the `status` being changed using the setter method. Perhaps remove the `setStatus` method, since we return a new `Person` instance every time we make edits to a Person.

2023-03-19 12:35 UTC, Merrickneo commented on src/main/java/seedu/address/model/person/Person.java
> +    private void setStatus(Status status) {
Since we create a new `Person` with a new status when we do a reject/advance, we should remove this setter method.

2023-03-19 15:16 UTC, Jxleejiaxin commented on src/main/java/seedu/address/model/person/Person.java
> +    private void setStatus(Status status) {
This occurred due to `Status` field being changed to `final` in master branch. Thus, setStatus is an illegal method as it attempts to modify what is `final`.

2023-03-19 23:47 UTC, Merrickneo approved these changes
LGTM! Thanks for the edits!

2023-03-19 23:47 UTC, merged