Implement RemindCommand
AY2223S2-CS2103T-W14-4/tp pull request #68
Opened 2023-03-17 13:25 UTC by dunliang0513

## What
Implement new function RemindCommand

## Why
Allow the hiring manager to have a quick view of the applicants who are going to have interviews in three days

## How
By using the `INTERVIEW_IN_THREE_DAYS_PREDICATE` allows me to filter the applicants whose current status is `SHORTLISTED`, and then filter them according to their interview time by using the `isWithinThreeDays` method which will only return true when the applicant's interview date is happening within three days.

2023-03-18 14:07 UTC, FredericChow00 reviewed
Left some minor comments but LGTM!

2023-03-18 14:07 UTC, FredericChow00 commented on src/main/java/seedu/address/logic/commands/RemindCommand.java
> +        model.updateFilteredPersonList(INTERVIEW_IN_THREE_DAYS_PREDICATE);
I think perhaps you could put the logic for this method into `execute()` then instead of having a getSuccessMessage(), u can just call the `MESSAGE_SUCCESS_FORMAT` static variable whenever u need the success message

2023-03-18 14:08 UTC, FredericChow00 commented on src/main/java/seedu/address/logic/commands/RemindCommand.java
> +
Can also consider adding an `equals()` method similar to other commands where the method checks whether the predicates are the same

2023-03-19 05:45 UTC, dunliang0513 commented on src/main/java/seedu/address/logic/commands/RemindCommand.java
> +        model.updateFilteredPersonList(INTERVIEW_IN_THREE_DAYS_PREDICATE);
The purpose of using `getSuccessMessage` is because I trying to maintain the consistency of our code, since the `InterviewCommand` is also implemented using `getSuccessfulMessage` and calls this function in the `execute`, I not too sure if should I follow it or follow the way you mention? Maybe we should discuss a way that we all agree to

2023-03-19 15:36 UTC, Jxleejiaxin requested changes
Please look at my second comment. Everything else looks good!

2023-03-19 15:36 UTC, Jxleejiaxin commented on src/main/java/seedu/address/logic/commands/RemindCommand.java
> +        model.updateFilteredPersonList(INTERVIEW_IN_THREE_DAYS_PREDICATE);
I think `getSuccessMessage` is fine. As @dunliang0513 mentioned, it is consistent with the code of our other commands. Additionally, should `RemindCommand` become more complicated due to further extension, we would not need to re-implement the `getSuccessMessage` method.

2023-03-19 15:36 UTC, Jxleejiaxin commented on src/main/java/seedu/address/model/person/InterviewDateTime.java
> +    }
From what I read in Java API, `Period.between` can return a negative value. In this case, `daysFromNow <= 3` will return true as long as the interview date is less than a month ago. Since we only want to remind users of future interview dates, this could be a possible bug!

2023-03-20 14:16 UTC, dunliang0513 commented on src/main/java/seedu/address/model/person/InterviewDateTime.java
> +    }
Yea you are right, I have added one additional condition to check for the `daysFromNow` to ensure that it will larger or equal to 0.

2023-03-21 15:24 UTC, FredericChow00 commented on src/main/java/seedu/address/logic/commands/RemindCommand.java
> +        model.updateFilteredPersonList(INTERVIEW_IN_THREE_DAYS_PREDICATE);
Oh ok! Because for me when I implemented the AdvanceCommand and RejectCommand, I did most of the work in the `execute()` method and used the static variable to get the format of the success message, but I think it's fine. We can change it if we have time

2023-03-22 08:24 UTC, merged