Editing User Guide: Commands
AY2223S2-CS2103T-W14-4/tp pull request #81
Opened 2023-03-20 16:52 UTC by bofeng1999

This PR adds the Command segment to the User Guide.

2023-03-21 04:33 UTC, Merrickneo requested changes
Suggested some minor edits to help with consistency!

2023-03-21 04:33 UTC, Merrickneo commented on docs/UserGuide.md
> +🚨NOTE
For standardisation purposes, try to make use of the different info blocks that Frederic used.

I've attached them here for your use:

`Alert Blocks`

<div markdown="span" class="alert alert-info" role="alert">:information_source: <strong>Note:</strong>
Highlight and display information you should pay attention to. </div>

<div markdown="span" class="alert alert-success" role="alert">:bulb: <strong>Tip:</strong>
Highlight tips which you might find useful. </div>

<div markdown="span" class="alert alert-danger" role="alert">:exclamation: <strong>Caution:</strong>
Highlight dangers and things to look out for. </div>


Links:
<a href> Phrases underlined in blue </a> are hyperlinks that will bring you to another part of
this documentation that is relevant to the phrase.

2023-03-21 04:33 UTC, Merrickneo commented on docs/UserGuide.md
> +
Maybe you can elaborate on how Individuals are identified by their name and phone number and also how the name provided is case-sensitive.

2023-03-21 04:33 UTC, Merrickneo commented on docs/UserGuide.md
> +Address: 7 Sims Drive (s)543212; Status: SHORTLISTED; Tags: [Python] [Java]`
Not sure if we want to name `notes` as `tags`
@bofeng1999 @Merrickneo @dunliang0513 @Jxleejiaxin @FredericChow00

2023-03-21 05:37 UTC, bofeng1999 commented on docs/UserGuide.md
> +🚨NOTE
Noted!

2023-03-21 05:50 UTC, bofeng1999 commented on docs/UserGuide.md
> +
good point thank you!

2023-03-21 08:03 UTC, Merrickneo approved these changes

2023-03-21 14:55 UTC, FredericChow00 reviewed
Left some comments but LGTM for the first UG Draft!

We will also likely be changing most outputs to pictures once we finalize our GUI

2023-03-21 14:55 UTC, FredericChow00 commented on docs/UserGuide.md
> +Find out more about restrictions in the sections [Flags](#flags), [Placeholders](#placeholders) and [Commands](#commands).
Need to change `placeholder` in glossary to `placeholders` so that this hyperlink works

2023-03-21 14:55 UTC, FredericChow00 commented on docs/UserGuide.md
> +This section shares with you on how to use each [[ command ]] in detail.
not too surre if the `[[ ]]` works for the pop-up in these underlined words... need to check after merging

2023-03-22 01:09 UTC, dunliang0513 commented on docs/UserGuide.md
> +Address: 7 Sims Drive (s)543212; Status: SHORTLISTED; Tags: [Python] [Java]`
Yea I think so

2023-03-22 03:36 UTC, merged